### ISSUE TITLE
raise char limit to 256

### ISSUE THREAD

**Issue by gubatron** [miguelfreitas/twister-core#76] opened 2014-01-15 23:30 UTC
Twitter's 140 char limitation came from their want to interface with SMS.

As this is a p2p network, and SMS has moved a long way since twitter was born (everybody now has smartphones, etc.)

can we raise this annoying limit to 256 chars so that we can convey more interesting thoughts and quotes (without getting out of the 'microblogging' category?)

**Comment by Qqwy** [comment] 2015-05-19 00:27
To summarize so far:
1) People seem to agree that 140 is an outdated limit, and 256 is probably more natural in this modern age.
2) 'Decentralized Link Shortening' might be an option by sending a link as a separate message (which can be clearly differentiated from normal messages), which is linked to in some way by the normal message.
3) Attaching images (or music,video, other multimedia files) might be done by internally creating a torrent for these files, and starting seeding when the message is sent. In this way, we can decentralize these files as well.

**Comment by miguelfreitas** [comment] 2015-05-19 00:48
@Qqwy good summary.

I'd just note that (1) increasing the limit is something that needs a careful deployment planning. Limit is enforced by all peers and you certainly don't want to start getting banned by (torrent) peers who believe you are violating the rules, right?

So what i'd think that could be feasible is to code the change with a time restriction, so the new limit would only be valid at some point in future. This would hopefully give enough time to users to update to newer versions including the (time-disabled) new limit.

**Comment by kseistrup** [comment] 2015-07-24 07:20
Now another two months have passed.  What do we do to make this happen?  And what shoulds the limit be?

* https://twistnik.com/search?text=char+limit
* https://twistnik.com/search?text=character+limit

**Comment by Erkan-Yilmaz** [comment] 2015-07-24 07:49
See comment by @mrvdb above: >140 char could be changed in clients, without having to change twister "infrastructure" itself

**Comment by slr** [comment] 2015-07-25 07:48
@Erkan-Yilmaz yep, it's true.

meanwhile I like @iShift's [comment](https://github.com/miguelfreitas/twister-core/issues/76#issuecomment-32465448).

**Comment by kseistrup** [comment] 2015-07-25 07:54
Another thing:  Twister actually counts the number of UTF-8 chars.  From `twister.cpp`:

```C
    } else if( msgUtf8Chars > 140 ) {
```

which means up to 4×140=560 bytes, which again means that we could let people use up to 560 bytes per twist without worrying much.

**Comment by lohang** [comment] 2015-08-15 07:19
(1)Is it possible to implement something like this:

a) Splitting longer post function should be kept, no matter what the decided character limit is.

b) There should be a way to check/calculate the average length of a split post, periodically.

c) In response to what we see in b), the character limit can be adjusted with every *major release* of Twister. If there is a tendency to use more characters that the *current* limit, the limit can be adjusted accordingly.

(2) Splitting posts function should make sure urls don't get split

(3) To me it is very difficult to have a meaningful conversation within the limit of 140 characters. If we can have 256 characters, that surely is a good start. From what I have seen, people who post to Twister don't generally expect the same notice to appear on Twitter - which is the only social media platform that restricts users to 140 limit. I personally prefer having no limits at all, but then this will stop being a *microblogging* service. So having some limit is okay :-)

**Comment by blog2read** [comment] 2015-10-20 06:34
Yes - 140 characters are really outdated - why copy #twitter here? It could be more then 256 - so then it is possible to write two ore three sentences. I don't see to implement it as "splitted" - this makes a text unreadable. Yes please - on my GS instance I have 1024 - that's cool.

**Comment by jpfox** [comment] 2015-10-20 07:27
Yes 140 chars is too short. In fact it is more difficult to write a message for some languages like german or french where words and syntax use more characters than english (sorry, I don't know asian language structure). And yes 256 seems to be a good choice : longer than actual restriction but not too long to be able to read rapidly stream of twists. 256 UTF8 chars always fits in 1kb.
Idea for specific additional fields like url or language code (which can be used to filter stream on languages you understand) is very good too. Often, long url uses to many characters in the twists message.

That's my opinion :-)

**Comment by miguelfreitas** [comment] 2016-03-19 17:16
Let's recap what message size limitations we currently have (hard) coded in twister and have a frank discussion about it.

1) acceptSignedPost
- checks for whole (bencoded) post size <= 2048
- checks "msg" field number of utf8 chars between 0 and 140 (0 is ok)

2) node_impl::incoming_request (DHT's "putData" primitive)
- checks for whole (bencoded) post size <= 768 for multi posts resources (replies and hashtags, but not for individual posts)
- checks for whole (bencoded) post size <= 8192 for individual posts.

These two function have different usages.

While (2) is used just for accepting/reject DHT resources, (1) is used pretty much everywhere. 

The consequence of violating (2) is not severe: some posts will not store on multi-item DHT (replies/hashtags) but will continue storing fine as individual DHT entries. Then if we increase the limit they will get stored again as users start upgrading their twisterd clients.

It is (1) that worries me...

The problem is that this function is also where signature is checked, and it is called from libtorrent's code while validating pieces. So if we change the validation rule, older clients will be in disagreement about whether the piece is good or not. Receiving an "invalid" piece multiple times will cause peers to ban newer clients who seem to be "misbehaving". Therefore I'm somewhat afraid of triggering this backward incompatibility and degrating the network.

One possible idea is to overflow extra text from "msg" field into another "msg2" field. That will cause older UI clients to just display part of the text, but does not cause any incompatibilities.

Comments?

**Comment by stman** [comment] 2016-03-19 17:47
Hello Miguel, and all other contributors,

Just a little info.

FYI guys, as I have been designing SMS/MMS routers connected to GSM's SMSC's in a previous Start-Up (NEOTIS TELECOM), I can ensure you that the 140 char limitation is not a limit. Original GSM Standard says that SMS of 140 char can be concatenated up to 4 SMS's if I remember well said Standard. If you want, I can dive again into the relevant GSM standard and show you the page where these few things are defined to check with up to how many concatenated SMS any basic GSM handset can manage & must be compatible with.

**Comment by stman** [comment] 2016-03-19 18:39
Ok, then, I have the answer about the SMS messages limitations according to the original GSM Standard. Please download the "SMS Short Message Service" Core GSM Standard here : [http://www.etsi.org/deliver/etsi_ts/100900_100999/100901/07.05.00_60/ts_100901v070500p.pdf](url) 

Then go to page 63, and start reading section 9.2.3.24.1 but also section 9.2.3.24.8 page 68, and you will know everything you need to know about GSM SMS message size limitations....

**Comment by miguelfreitas** [comment] 2016-03-19 19:12
Thanks @stman but i'm not much worried about SMS anymore... People convinced me we don't need to care. I'm worried about compatibility within our own protocol.

**Comment by stman** [comment] 2016-03-19 19:39
Excuse me @miguelfreitas , I did read the post too rapidly, and didn't see somebody had already given some infos about concatenated SMS.... Glad to hear you don't worry any longer about msg size anyway :-)

**Comment by jpfox** [comment] 2016-03-19 22:31
miguel, you know as no one how twister works and your analyse seems good. Spliting overlapping text to a msg2 field is a good idea. it can garantee retro compatibility and network stability. I encourage you to work in this direction

**Comment by mrvdb** [comment] 2016-03-20 10:05
Have we exhausted the options without changing the underlaying protocol? It seems to me, but I may be missing something, there is enough information for client software to re-assemble messages which have been split.

It _feels_ like this problem should not be solved in the transport layer.

**Closed** 2016-03-25 23:47 UTC
